### ISSUE TITLE
token not cached?

### ISSUE THREAD

**Issue by sevenEng** [me-box/lib-node-databox#28]
In the new store API, tokens are not cached, `requestToken` would go to arbiter directly: https://github.com/me-box/lib-node-databox/blob/master/lib/utils.js#L126-L132, or it's cached somewhere else?
but the go version seems fine: https://github.com/me-box/lib-go-databox/blob/master/utils.go#L150

**Comment by Toshbrown** [comment]
Good spot, I will get this fixed. 

The old API used makeStoreRequest which does the caching.

**Comment by Toshbrown** [comment]
Fixed in https://github.com/me-box/lib-node-databox/pull/34
