### ISSUE TITLE
Get token error when registering datasource

### ISSUE THREAD

**Issue by psyaoc** [me-box/lib-node-databox#29]
Using the code [here](https://github.com/psyaoc/databox-driver-moves/blob/master/routes/index.js#L36) I cannot seem to register a datasource, I've tried many different examples using what is shown in lib-node-databox/test as well as other drivers.

Error: `GET TOKEN ERROR::Target driver-moves-core-store has not registered itself for arbitering`

I have tried calling this code after a delay with setTimeout but the same issue occurs.

Using Databox 0.3.1 and the latest version of node-databox.

Any help would be much appreciated, thanks.

**Comment by Toshbrown** [comment]
Let me just try it here

**Comment by psyaoc** [comment]
Running on Ubuntu 16.04 at the moment

**Comment by Toshbrown** [comment]
works for me ;-)

```
Toshs-MacBook-Pro:~ tosh$ d service logs driver-moves -f
driver-moves.1.xhjy7tj6x5y0@linuxkit-025000000001    |
driver-moves.1.xhjy7tj6x5y0@linuxkit-025000000001    | > databox-driver-moves@0.0.0 start /
driver-moves.1.xhjy7tj6x5y0@linuxkit-025000000001    | > node ./bin/www
driver-moves.1.xhjy7tj6x5y0@linuxkit-025000000001    |
driver-moves.1.xhjy7tj6x5y0@linuxkit-025000000001    | DEBUG: Moves-Driver - Starting HTTPS Server
driver-moves.1.xhjy7tj6x5y0@linuxkit-025000000001    | Registered store: driverSettings
```

**Comment by psyaoc** [comment]
That's strange...

Does this look right to you?

![image](https://user-images.githubusercontent.com/20520093/35360374-6f79e1fe-0155-11e8-96c8-9645e6aeccf9.png)

**Comment by Toshbrown** [comment]
You're missing this 

```8d7e2b046c76        core-store:0.3.1                         "./main.exe"        5 minutes ago       Up 5 minutes        5555-5556/tcp                      driver-moves-core-store.1.6uz1gg3pdcueohb6edmyj7lzn```

look at the `./databox-install-component` script for tips 

looks like your missing core-store:0.3.1 

just do a `docker tag databoxsystems/core-store:0.3.1 core-store:0.3.1 `

**Comment by Toshbrown** [comment]
If the name of your repo matched the name of your app you could just use the `./databox-install-component` script.

e.g.

`./databox-install-component psyaoc/driver-moves` 

and it would build and tag everything you need

**Comment by psyaoc** [comment]
That has sorted it, thanks :) I'll rename the repo and stick to the install-component script from now on.
