### ISSUE TITLE
Incorrect store read

### ISSUE THREAD

**Issue by psyaoc** [me-box/lib-node-databox#32]
Hi,

I seem to be able to read the content of a datasource using the incorrect datasource id, this has been happening to me occasionally and I can only reproduce this by frequently refreshing my application.

Code:

![image](https://user-images.githubusercontent.com/20520093/36153965-d9880892-10c7-11e8-90e0-8b572bb3d765.png)

Output:

![image](https://user-images.githubusercontent.com/20520093/36153810-5dca7604-10c7-11e8-9478-73012efd6014.png)

The correct response (which I received on the next refresh, looks like this):

![image](https://user-images.githubusercontent.com/20520093/36153899-adfee6e6-10c7-11e8-99a6-c0c677f483b2.png)

**Comment by Toshbrown** [comment]
Thanks for the bug report. 

Looks like the problem is here https://github.com/Toshbrown/nodeZestClient/blob/master/zest.js#L68

I'll try and get it fixed today/tonight.

Cheers

Tosh

**Comment by Toshbrown** [comment]
Did this fix the issue? I did not get time to fully test it. 

If it's working I will merge #33 for you.

**Comment by psyaoc** [comment]
Hi, I've been trying to test but I don't believe that I am forcing lib-node-databox to use 0.0.11 of the zest client correctly, at the moment the issue is still there.

I've tried several approaches but both versions always seem to show up:

`npm list | grep zest`

```
| +-- nodezestclient@0.0.9
-- nodezestclient@0.0.11
```

I have `"nodezestclient": "0.0.11"` in my package.json but i have also tried removing it from package.json and also as a requirement from node-databox in package-lock.json, then adding version 0.0.11 as a separate dependency in the package-lock file. I'm not too familiar with NPM so the chances are I'm making an error somewhere.

Thanks for the reply.
