### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by pszjac** [me-box/lib-node-databox#38]
Docs need updating for 0.4.0 specifically: 

* timeseries blob client needs documenting
* requirements of value field in time series write needs documenting
* need to document that time series write json supports at most 1 tag field with a string

* need to document where to get reqEndpoint from (both as a driver and for datasources in apps)
* need to document that process.env["DATASOURCE_XXX"] returns the meta data for that datasource required to connect to the store and make a client

**Comment by haddadi** [comment]
and perhaps a hint to where to get the password from for the dashboard in case someone is not terminal friendly.

**Comment by Toshbrown** [comment]
Had a go at updating the docs here https://github.com/me-box/lib-node-databox/tree/update-docs feedback welcome.

**Comment by Toshbrown** [comment]
Updated in https://github.com/me-box/lib-node-databox/pull/40
